### ISSUE TITLE
Adding info about missing requirements for crystal to installing on MacOS

### ISSUE THREAD

**Issue by 5minpause** [luckyframework/website-old#12]
The issues I had when starting out with Lucky were related to Crystal, but that wasn't clear to me due to no previous experience with Crystal.

These where my issues:
```
Package libssl was not found in the pkg-config search path.
Perhaps you should add the directory containing `libssl.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libssl' found
Package libcrypto was not found in the pkg-config search path.
Perhaps you should add the directory containing `libcrypto.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libcrypto' found
ld: library not found for -lssl
```

I solved it by adding `export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` to my `~/.zshrc.local`.

Should I open a PR to add this to the appropriate section, or is this something that should be made clear somewhere else? Or not at all?
What do you think?

**Comment by paulcsmith** [comment]
@5minpause Ah yes that is an issue with macOS High Sierra I think. I think this should go in the installing guide https://github.com/luckyframework/website/blob/master/source/guides/installing.html.md.erb#L26

With a note like : "If you are on macOS Sierra you may need to add  `export PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig` to your `~/.bashrc` or `~/.zshrc.local` file.

If you want to tackle that, feel free! If not, post here so myself or someone else can add it. Thanks for reporting!

**Comment by CorbanR** [comment]
created pull https://github.com/luckyframework/website/pull/15 for this issue.

**Comment by paulcsmith** [comment]
Closed by https://github.com/luckyframework/website/commit/e74880efaaa49ff38b6169a922aeb549a5e60685

**Comment by Xosmond** [comment]
Hey guys I can't install lucky via brew yet, is it available?

**Comment by 5minpause** [comment]
@Xosmond have a look here https://github.com/luckyframework/cli
