### ISSUE TITLE
Document running custom queries

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website-old#133]
As discussed in https://github.com/luckyframework/lucky_record/issues/56#issuecomment-353073498

**Comment by paulcsmith** [comment]
Maybe @mikeeus could help? This would basically be something like his article here: https://dev.to/mikeeus/mapping-database-queries-to-crystal-classes-with-crystal-db-and-lucky-460i

**Comment by mikeeus** [comment]
Sure thing @paulcsmith, I'll make a PR for this tomorrow

**Comment by paulcsmith** [comment]
Awesome :D Thank you
