### ISSUE TITLE
MacOS Firewall keeps prompting for approval

### ISSUE THREAD

**Issue by snadon** [luckyframework/website-old#137]
If your MacOS firewall is enabled, it will keep prompting for approval.

I replaced `0.0.0.0` with `127.0.0.1` in `config/server.cr` and `config/watch.yml` to avoid this problem.

**Comment by paulcsmith** [comment]
I'm going to go ahead and close this for now since using `127.0.0.1` causes issues with BrowserSync and a few other things sometimes. There's not really a solid way around it as far as I know.

Hopefully if people run into this with the macOS firewall on they can use this issue to fix it!
