### ISSUE TITLE
Does it make sense to translate the guides

### ISSUE THREAD

**Issue by papilip** [luckyframework/website-old#142]
Middleman have i18n extension
https://middlemanapp.com/advanced/localization/

Does it make sense to translate the guides in other languages ? Do you prefer a separate site ?

Thank you in advance for your answer.

**Comment by paulcsmith** [comment]
Hi @papilip I think translations would be great but I think it'd be best to do it once the guides have stabilized and Lucky is 1.0. I'd also need to make sure someone was dedicated to keeping translations up to date so they don't get stale with new releases. For now I'll close this, but I'll add a label to revisit it later when the guides have stabilized!
