### ISSUE TITLE
Add Guide for API usage

### ISSUE THREAD

**Issue by beanieboi** [luckyframework/website-old#16]
Hey,

I'm just playing around with Lucky and wanted to built a small JSON API. After installing I noticed that there is a lot of Javascript/Node modules that I don't need. It would be really cool to have some Guides on how to avoid all the Javascript things if you don't need them.

Thank You!

**Comment by paulcsmith** [comment]
Thanks so much for the suggestion. I’m prioritizing some of the other guides first, but I will *definitely* Add one for working with JSON for REST APIs!

**Comment by paulcsmith** [comment]
Closed by #81
