### ISSUE TITLE
existing module ?

### ISSUE THREAD

**Issue by remydev** [luckyframework/website-old#177]
Good morning,
I discover luky and crystal, that interests me a lot, but coming from the world of django, or finally everything already exists under with modules, I would like to know if there are simple additional modules, like blog or admin panel ?
Thanks

**Comment by paulcsmith** [comment]
Hi @remydev!

There is no additional library for blog or admin panel, but I want to create a nice admin panel in the future.

In the next version of Lucky you will be able to generate actions and pages more easily which should help with building CRUD apps.

Thanks for asking! BTW, feel free to hop on https://gitter.im/luckyframework/Lobby if you have any other questions
