### ISSUE TITLE
Forgot to inherit from MainPage on NewPage

### ISSUE THREAD

**Issue by Xosmond** [luckyframework/website-old#31]
https://github.com/luckyframework/website/blob/fdeaa6ff707a602e2a63f4f858a142d4506a3279/source/guides/saving-with-forms.html.md.erb#L89

Forgot to inherit from MainPage.

**Comment by paulcsmith** [comment]
Good catch! If you’d like to submit a PR for  that it’d be great, but if not I can tackle it later
