### ISSUE TITLE
Add something about thoughtbot in footer like we have with TMWIC

### ISSUE THREAD

**Issue by paulcsmith** [luckyframework/website-old#52]
https://tellmewhenitcloses.com/session/new

<img width="260" alt="screen shot 2017-11-17 at 4 40 53 pm" src="https://user-images.githubusercontent.com/22394/32970225-1a35fd56-cbb6-11e7-85a8-5bbf05832fc8.png">

**Comment by jwoertink** [comment]
Maybe this should be closed now? lol 😂

**Comment by paulcsmith** [comment]
.....🤪

**Comment by paulcsmith** [comment]
Still made with ❤ though
